"""Protocol interfaces for Tinker backend service contracts."""

from __future__ import annotations

from typing import Any, Protocol

from tinker_backend.protocol.schemas import (
    CreateSessionResponse,
    FutureResponse,
    GetStepResponse,
    OpenAIChatPrompt,
    RuntimeHeartbeatResponse,
    RuntimeStatusResponse,
    SessionHeartbeatResponse,
)


class TinkerBackend(Protocol):
    """Core backend operations: sessions, runtimes, async operation tracking."""

    async def create_session(self, *, tags: list[str], sdk_version: str, project_id: str | None, user_metadata: dict[str, Any] | None) -> CreateSessionResponse: ...
    async def create_runtime(self, *, runtime_type: str, config_type: str, config_content: str, session_id: str | None) -> FutureResponse: ...
    async def retrieve_future(self, *, request_id: int) -> dict[str, Any]: ...
    async def runtime_heartbeat(self, *, runtime_id: str, status: str, ready: bool, adapter_base_url: str | None, process_pid: int | None, error_message: str | None) -> RuntimeHeartbeatResponse: ...
    async def get_runtime(self, *, runtime_id: str) -> RuntimeStatusResponse: ...
    async def close_runtime(self, *, runtime_id: str, force_after_seconds: float | None) -> FutureResponse: ...
    async def session_heartbeat(self, *, session_id: str) -> SessionHeartbeatResponse: ...


class AgenticBackend(Protocol):
    """Agentic/RL extension: task environments, steps, sampling, training ops."""

    async def init_task_env(self, *, runtime_id: str, task_id: str, dataset: str, split: str, metadata: dict[str, Any] | None) -> FutureResponse: ...
    async def get_step(self, *, runtime_id: str, env_id: str, step_id: int | None) -> GetStepResponse: ...
    async def sample(self, *, runtime_id: str, env_id: str | None, prompt: OpenAIChatPrompt | None, model_input: dict[str, Any] | None, sampling_params: dict[str, Any] | None, num_samples: int) -> FutureResponse: ...
    async def forward_backward(self, *, runtime_id: str, data: list[dict[str, Any]], loss_fn: str) -> FutureResponse: ...
    async def forward(self, *, runtime_id: str, data: list[dict[str, Any]], loss_fn: str) -> FutureResponse: ...
    async def optim_step(self, *, runtime_id: str, model_id: str | None) -> FutureResponse: ...
    async def save_weights(self, *, runtime_id: str, path: str) -> FutureResponse: ...
    async def load_weights(self, *, runtime_id: str, path: str, optimizer: bool) -> FutureResponse: ...
