from typing import Optional

from typing_extensions import Literal

from .._models import BaseModel

__all__: list[str] = ["PublishToSamplerResponse", "PublishToSamplerResponseInternal"]


class PublishToSamplerResponseInternal(BaseModel):
    path: str | None = None
    """A tinker URI for sampler weights when a persistent publish was requested."""

    sampling_session_id: str | None = None
    """The sampling session generated by an ephemeral publish."""

    type: Optional[Literal["publish_to_sampler"]] = None


class PublishToSamplerResponse(BaseModel):
    path: str | None = None
    sampling_session_id: str | None = None

    type: Optional[Literal["publish_to_sampler"]] = None
