experiment_id: SWE-bench-test
timeout: 7200
environment:
  base_url: https://xrl.alibaba-inc.com
  xrl_authorization: ""
  image: rock-instances-registry-vpc.cn-shanghai.cr.aliyuncs.com/instance/harbor:9f2a8b2b759
  memory: 16g
  cpus: 4
  startup_timeout: 1800
  env: {}
  oss_mirror:
    enabled: true
agents:
  - name: swe-agent
    model_name: openai/default
    kwargs:
      api_key: ""
      api_base: ""
orchestrator:
  n_concurrent_trials: 1
datasets:
  - registry:
      split: test
    name: princeton-nlp/SWE-bench_Verified
    task_names: [""]
verifier:
  disable: false
