"""Auto-generated literal aliases derived from ``SandboxInfo``.

Do not edit this file manually. Regenerate via:
    uv run python tools/generate_sandbox_info_types.py
"""

from typing import Literal

SandboxInfoField = Literal[
    "host_ip",
    "host_name",
    "image",
    "user_id",
    "experiment_id",
    "namespace",
    "cluster_name",
    "sandbox_id",
    "auth_token",
    "rock_authorization_encrypted",
    "phases",
    "state",
    "port_mapping",
    "create_user_gray_flag",
    "cpus",
    "memory",
    "create_time",
    "start_time",
    "stop_time",
]
