#!/usr/bin/env python3
"""Generate sandbox TypedDict literal aliases.

Usage:
    uv run python tools/generate_sandbox_info_types.py
"""

from __future__ import annotations

import ast
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_FILE = REPO_ROOT / "rock/actions/sandbox/sandbox_info.py"
TARGET_FILE = REPO_ROOT / "rock/actions/sandbox/_generated_types.py"


def _extract_sandbox_info_fields(source: str) -> list[str]:
    module = ast.parse(source)
    for node in module.body:
        if isinstance(node, ast.ClassDef) and node.name == "SandboxInfo":
            fields: list[str] = []
            for stmt in node.body:
                if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
                    fields.append(stmt.target.id)
            if not fields:
                raise RuntimeError("SandboxInfo has no annotated fields")
            return fields
    raise RuntimeError("SandboxInfo TypedDict class not found")


def _render_generated(fields: list[str]) -> str:
    lines = [
        '"""Auto-generated literal aliases derived from ``SandboxInfo``.',
        "",
        "Do not edit this file manually. Regenerate via:",
        "    uv run python tools/generate_sandbox_info_types.py",
        '"""',
        "",
        "from typing import Literal",
        "",
        "SandboxInfoField = Literal[",
    ]
    lines.extend([f'    "{field}",' for field in fields])
    lines.extend(["]", ""])
    return "\n".join(lines)


def main() -> None:
    source = SOURCE_FILE.read_text(encoding="utf-8")
    fields = _extract_sandbox_info_fields(source)
    generated = _render_generated(fields)
    TARGET_FILE.write_text(generated, encoding="utf-8")
    print(f"Generated {TARGET_FILE.relative_to(REPO_ROOT)} with {len(fields)} fields.")


if __name__ == "__main__":
    main()
